name: Build and Test
on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        node: [12, 14, 16]
    name: ${{ matrix.os }} and node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - name: Build
        run: npm run build:release
      - name: Test
        run: npm run test:headless
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: Utilities/TestResults/Test-Report.html
          retention-days: 15